### PR TITLE
[skip ci] Removing former Grunts

### PR DESCRIPTION
**Pull request by eak12913**
[skip ci] Removing former Grunts

### CODE REVIEW

**Comment by ryehowell** [comment]
@eak12913, it looks like the changes in this PR are only for the ordering of the names, but no changes otherwise. Is this needed?

**Comment by eak12913** [comment]
I was running a script that removed folks who have since moved on from Gruntwork. At the same time I figured that I'd alphabetize the existing entries. This repo had no one to remove, but it sorted the existing members. The idea would be to standardize the codeowners file. Not strictly needed but it would make things more consistent.

**Review by ryehowell — APPROVED** [review]
LGTM

**Comment by ryehowell** [comment]
Hi @eak12913 , did you want me to handle getting this merged and closed? Wasn't sure if you had some automation in place that would handle that as well. Just let me know!

**Comment by MoonMoon1919** [comment]
@ryehowell go ahead and merge at will, thanks!

**Pull request merged**
