### PR TITLE
Update helm documentation to focus on helm 3

### PR DESCRIPTION
**Pull request by yorinasub17**

### CODE REVIEW

**Comment by zackproser** [comment]
Do you think it would be appropriate to state explicitly somewhere in the docs that we are using Helm 3 now? I think enough developers are aware of the significant changes between 2 and 3 with the removal of the server side component.

**Comment by yorinasub17** [comment]
I don't really want to mention that yet, as this chart still works with 2 and 3. Don't want to give the false impression that this doesn't work on helm 2.

**Comment by zackproser** [comment]
> I don't really want to mention that yet, as this chart still works with 2 and 3. Don't want to give the false impression that this doesn't work on helm 2.

Roger that - makes sense.

**Comment by yorinasub17** [comment]
Thanks for review! Merging this in now. Forgot to hit merge button...

**Pull request merged**
