### PR TITLE
Add version compatibility to the HPA API

### LINKED ISSUE #145: Missing HPA capability for Kubernetes 1.23
**Describe the solution you'd like**
When the HPA of the chart is enabled, it does not deploy on Kubernetes versions >= 1.23 because of the deprecation of the `autoscaling/v2beta2` API.

**Describe alternatives you've considered**
Use `autoscaling/v2` API for Kubernetes versions >= 1.23

**Additional context**
-

### PR DESCRIPTION
**Pull request by paul-pop**
## Description

Fixes #145.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Use `autoscaling/v2` API for Kubernetes versions >= 1.23.

### CODE REVIEW

**Comment by paul-pop** [comment]
@yorinasub17 👋 

Any chance for a quick look and this a potential release so k8s 1.23 gets the support it needs?

**Review by autero1 — COMMENTED** [review]
Thanks for the PR @paul-pop !

Overall, this LGTM! 

Could you add a render test for the HPA in `k8s_service_template_test.go`? Note that this also requires updating the `k8s.io` dependencies in `go.mod` to get the new `autoscaling/v2` API.

**Comment by autero1** [comment]
Hi, sorry for the delay. I've kicked off the tests again.

**Comment by autero1** [comment]
All the tests failed on:
```
Running Go tests in  with command: go test -v -timeout 60m -parallel 128  -tags integration . -short
# sigs.k8s.io/json/internal/golang/encoding/json
../../.go_workspace/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
../../.go_workspace/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
FAIL	github.com/gruntwork-io/helm-kubernetes-services/test [build failed]
```

**Comment by paul-pop** [comment]
Closing as #151 was merged with the changes.

**Pull request closed without merging**
