### PR TITLE
[IAC-1677] Replace gofmt with goimports

### PR DESCRIPTION
**Pull request by ina-stoyanova**
Replace gofmt with goimports in the pre-commit configuration. Note: This PR was opened using git-xargs.

### CODE REVIEW

**Comment by zackproser** [comment]
This one is failing because the `go` binary is not resolvable via the `PATH` when the `go mod tidy` command in the `setup` job is run. 

I started digging into why. I've been running the build locally with the help of [the Circle CI CLI ](https://circleci.com/docs/2.0/local-cli/?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gb-DSA-Eng-uscan&utm_content=&utm_term=dynamicSearch-&gclid=CjwKCAjwoZWHBhBgEiwAiMN66SEHzcuwp_2xdZhJpbJmaA79g0Pj2SjKMQ2qXpu8JtGbXLHGbQy14RoCVScQAvD_BwE)and this command to just run the failing `setup` step: 

```
circleci local execute --job setup --env GITHUB_OAUTH_TOKEN=$GITHUB_OAUTH_TOKEN
```


When we first call `install_gruntwork_utils` we in turn call `configure-environment-for-gruntwork-module` with the configured `go-version` [here](https://github.com/gruntwork-io/terraform-aws-ci/blob/master/modules/gruntwork-module-circleci-helpers/bin/configure-environment-for-gruntwork-module#L229).

This leads to a symlink from `/usr/local/go/bin/go` to `/usr/bin/go` being created.

However, it seems when this binary attempts to query `go`[ to confirm the installed version](https://github.com/gruntwork-io/terraform-aws-ci/blob/master/modules/gruntwork-module-circleci-helpers/bin/configure-environment-for-gruntwork-module#L233) it fails: 

```
/usr/local/bin/configure-environment-for-gruntwork-module: line 211: go: command not found     
The installed version of Go is now 
```

**Comment by zackproser** [comment]
Took a stab at a fix in 8ddf86b.

**Review by yorinasub17 — APPROVED** [review]
LGTM!

**Comment by ina-stoyanova** [comment]
Wow! Thanks @zackproser! I'll merge this one, but will leave the honours of releasing it for you, since the majority of contribution here is yours! Really appreciate it 🎉

**Comment by zackproser** [comment]
@ina-stoyanova all yours - but thank you! :+1:  Just added that on because I've been running into similar issues recently with my own git-xargs PRs.

**Comment by ina-stoyanova** [comment]
Thanks, Zack! Merging this one now!

**Pull request merged**
