### PR TITLE
171 inject Secret Store CSI driver `deployment_spec.tpl`

### LINKED ISSUE #171: feature: Inject Secret Store CSI driver to deployment_spec
## Related

Add support for CSI volume mounts - https://github.com/gruntwork-io/helm-kubernetes-services/issues/118

## Description

When we want to use a Secret Store CSI driver, we need to include a 'csi' block in the 'secrets' section of the values.yaml. This will inject some content into the Volume and Environment Variables sections of the deployment.

I created a template test to check if the YAML is correctly built ✅

We now accept 'secret.as' to have the type 'csi'. This will add an environment variable to the container for each secret and also include the 'csi' block in the volume.

My issue (and the reason, in my humble opinion, why nobody picked up this ticket) arises when creating the integration test.

In our organization's use-case, we are using AWS Secret Manager, but the implementation of this injection should be generic.

For that reason, within the test, we would need to provision Minikube with Consul Vault and the Secret Store CSI driver Helm charts before we can add a custom resource that includes the secret provider class.

 It feels like it's beyond the scope to add custom resources, but it's necessary to be able to test the pod was created correctly and the secrets mounted as env vars

integration test hasn't been added ❌ 

waiting for confirmation that  provisioning consul+Vault on  minikube and adding the secret store crd is the correct approach  for adding an integration test. Another thing, is it necessary to provide an integration test for this case?

### PR DESCRIPTION
**Pull request by omar-devolute**
## Description

Fixes #171 . Can be considered part (subtask) of #118 

In the deployment_spec.tpl we must allow a new "**as**" value to be passed to a secret block, we call this new type "csi".

Receiving this type of a secret, the tpl has to mix functionality of both volumes and environment types, as we will require a env block and a volumeMounts block

## Steps

- [x] add template test - to check a csi block is passed to the secret
- [x] modify deployment_spec.tpl so that it can accept  "csi" for the values of the "as"  and test the template builds appropriately 

## TODOs

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes.

## Release Notes

Allow secret of type csi, inject Secret Store CSI related fields to deployment spec Env and Volumes

### CODE REVIEW

**Comment by ryehowell** [comment]
Hi @omar-devolute, thanks for this contribution! I am going to add this to our project backlog so it gets into our queue for review.

**Comment by ryehowell** [comment]
Hi @nadiia-caspar, thanks for following up! I am hoping to get to this soon. We have it in the queue for review. Hoping to take a look by the end of the week. Thanks for your patience!

**Comment by ryehowell** [comment]
@nadiia-caspar @omar-devolute I just kicked off CI build. Will be reviewing this shortly.

**Comment by ryehowell** [comment]
Looks like there are some CI test failures. I think it is due to a small regression that is noted in the review.

**Comment by nadiia-caspar** [comment]
@ryehowell i have to take over this PR, could you please help me to complete it?

**Comment by ryehowell** [comment]
Hi @nadiia-caspar, how can I help? Is there something specific that you need assistance with?

**Comment by nadiia-caspar** [comment]
Hi @ryehowell i made some changes (not sure what helped exactly 😄) but the template tests are now successful. The integration tests we didn't add, the because it would require the installation of the Secret Store CSI driver Helm chart. So I guess now you can review the PR. Let me know if any changes are required

**Review by ryehowell — APPROVED** [review]
Changes look good. Thanks for the contribution!

**Comment by nadiia-caspar** [comment]
@ryehowell do you know when the release with these changes will be available in the helm repo?

**Comment by ryehowell** [comment]
The latest version will be released at some point later today @nadiia-caspar and will be available in the Gruntwork Helm chart repo. I can send a message once the release has been completed and the latest version of the chart is available.

**Comment by nadiia-caspar** [comment]
@ryehowell thanks for the update, don't worry I will check the repo later today/tomorrow :)

**Pull request merged**
