### PR TITLE
Add priorityclassname Support and Test

### LINKED ISSUE #159: Support priorityClassName
**Describe the solution you'd like**
Support for `priorityClassName` (stable as of k8s v1.14) to assign a PriorityClass to deployments creating using the k8s-service helm chart.

**Describe alternatives you've considered**
I am not aware of a viable alternative method of adding `priorityClassName` to k8s-service based deployments other than adding support to the helm chart.

**Additional context**
[priorityClassName documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority)

### PR DESCRIPTION
**Pull request by reynoldsme**
## Description

Fixes #159.

This PR introduces suport for [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) and adds the `TestK8sServicePriorityClassName` test.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs*.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

*documented in values.yaml. I'm happy to add something to `/charts/k8s-service/README.md` if that is determined to be necessary.

## Release Notes (draft)

Added support for priorityClassName.

### CODE REVIEW

**Comment by josh-padnick** [comment]
@ryehowell Could you take a look at this when you get a chance? 'cc @gitsstewart

**Comment by ryehowell** [comment]
Hey @reynoldsme, thanks for the contribution! I'm wrapping up a couple other PR's at the moment, but will review this next. It probably won't be until tomorrow though. I went ahead and kicked off the CI build as well.

**Review by ryehowell — APPROVED** [review]
These changes look good to me. CI build is green as well.

**Review by zackproser — APPROVED** [review]
LGTM

**Pull request merged**
